# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: poktrolld-relayer-scripts
# data:
#   poktroll.sh: |-
#     #!/bin/sh

#     ls -la /root/.poktroll/config-src/
#     mkdir -p /root/.poktroll/config/
#     cp -r -L /root/.poktroll/config-src/* /root/.poktroll/config/
#     ls -la /root/.poktroll/config/

#     # sleep 99999

#     # Start the node
#     poktrolld relayer --node tcp://poktrolld:36657 --ws-url ws://poktrolld:36657/websocket --signing-key servicer1 --keyring-backend test

#     # OR debug the node (uncomment this line but comment previous line)
#     # dlv exec /usr/local/bin/poktrolld relayer --node tcp://poktrolld:36657 --ws-url ws://poktrolld:36657/websocket --signing-key servicer1 --keyring-backend test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anvil
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anvil
  template:
    metadata:
      labels:
        app: anvil
    spec:
      containers:
        - name: anvil
          image: ghcr.io/foundry-rs/foundry:latest
          ports:
            - containerPort: 8547
          command: ["anvil"]
          args: ["-p", "8547", "-b", "5", "--host", "0.0.0.0"]
---
apiVersion: v1
kind: Service
metadata:
  name: anvil
spec:
  selector:
    app: anvil
  ports:
    - protocol: TCP
      name: rpc
      port: 8547
      targetPort: 8547