---
apiVersion: v1
kind: ConfigMap
metadata:
  name: poktrolld-servicer-scripts
data:
  poktrolld.sh: |-
    #!/bin/sh

    # start the servicer
    poktrolld servicer --from=ADDKEY
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: read-secrets
#   namespace: default  # Replace with the namespace where the secret resides
# subjects:
# - kind: ServiceAccount
#   name: poktrolld
#   namespace: default  # Replace with the namespace where the service account resides
# roleRef:
#   kind: Role
#   name: secret-reader
#   apiGroup: rbac.authorization.k8s.io
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: secret-reader
#   namespace: default  # Replace with the namespace where the secret resides
# rules:
# - apiGroups: [""]
#   resources: ["secrets"]
#   verbs: ["get", "list"]
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: poktrolld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poktrolld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poktrolld
  template:
    metadata:
      labels:
        app: poktrolld
    spec:
      serviceAccountName: poktrolld
      containers:
      - name: poktrolld
        image: poktrolld
        # To allow Delve to do the thing
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add: ["SYS_PTRACE"]
        env:
          - name: AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: celestia-secret
                key: auth_token
        # ports:
        # - containerPort: 36657
        # - containerPort: 40004
        command: ["/bin/sh"]
        args: ["/scripts/poktrolld.sh"]
        volumeMounts:
        - name: scripts-volume
          mountPath: /scripts
        # - name: keys-volume
        #   mountPath: /root/.poktroll/keyring-test/
        # - name: configs-volume
        #   mountPath: /root/.poktroll/config-src/
        # - name: configs-volume
        #   mountPath: /root/.poktroll/config/app.toml
        #   subPath: app.toml
        # - name: configs-volume
        #   mountPath: /root/.poktroll/config/client.toml
        #   subPath: client.toml
        # - name: configs-volume
        #   mountPath: /root/.poktroll/config/config.toml
        #   subPath: config.toml
        # - name: configs-volume
        #   mountPath: /root/.poktroll/config/priv_validator_key.json
        #   subPath: priv_validator_key.json
        # - name: configs-volume
        #   mountPath: /root/.poktroll/config/node_key.json
        #   subPath: node_key.json
        # - name: configs-volume
        #   mountPath: /root/.poktroll/config/genesis.json
        #   subPath: genesis.json
      volumes:
      - name: scripts-volume
        configMap:
          name: poktrolld-servicer-scripts
      # - name: keys-volume
      #   configMap:
      #     name: poktrolld-servicer-keys
      # - name: configs-volume
      #   configMap:
      #     name: poktrolld-servicer-configs
